[package]
name = "rpubsub"
version = "0.1.0"
edition = "2021"

[dependencies]
zmq = "0.9"
strum = "0.24"
strum_macros = "0.24"
serde = {version = "1.0.145", features = ["derive"]}
serde_json = {version = "1.0"}
sha2 = {version="0.10.6"}

[lib]
name = "rpubsub"
path = "./rpubsub.rs"